#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ff00ffcc'  # default
T='#555555ee'  # text
W='#880000bb'  # wrong
V='#bb00bbbb'  # verifying

i3lock \
--blur 2 \
--bar-indicator \
--bar-pos y+h \
--bar-direction 1 \
--bar-max-height 10 \
--bar-base-width 10 \
--bar-color 00000022 \
--keyhl-color ffffff \
--bar-periodic-step 50 \
--bar-step 50 \
--redraw-thread \
\
--clock \
--force-clock \
--time-pos x+550:y+h-585 \
--time-color 880088ff \
--time-str %l:%M:%S \
--date-pos  x+550:y+h-550 \
--date-color FFFFFF \
--date-size 30 \
--time-size 55 \
--time-color FFFFFF \
--date-align 1 \
--time-align 1 \
--ringver-color 8800ff88 \
--ringwrong-color ff008888 \
--status-pos x+5:y+h-16 \
--verif-align 0 \
--wrong-align 0 \
--verif-color ffffffff \
--wrong-color ffffffff \
--modif-pos -50:-50
